baseURL = 'https://sebastienhauri.ch/'
languageCode = 'en-us'
defaultContentLanguage = 'fr'
theme = 'hello-friend-ng'

title = 'Sébastien Hauri'
keywords = ""
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
# leave empty to disable, enter display text to enable
#lastModDisplay = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[author]
	name = "Sébastien Hauri"

[params]
	defaultTheme = 'dark'
	enableThemeToggle = true
	enableGlobalLanguageMenu = true
	#showMenuItems = 3
	homeSubtitle = 'Master student in cybersecurity'
	justifyContent = false

	[params.footer]
		trademark = true
		rss = true
		copyright = true
		author = true
		bottomText = [
		"Powered by <a href=\"http://gohugo.io\">Hugo</a>",
		"Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
		]

	[[params.social]]
		name = 'email'
		url = '/contact'

	[[params.social]]
		name = 'github'
		url = 'https://github.com/sebhauri/'

	[[params.social]]
		name = 'mastodon'
		url = 'https://fosstodon.org/@cryptangelo'

	[[params.social]]
		name = 'linkedin'
		url = 'https://linkedin.com/in/sebastien-hauri'

[taxonomies]
	tag      = "tags"
	category = "categories"
	series   = "series"

[languages]
	[languages.fr]
    	languageName = 'Français'
		weight = 1
		contentDir = 'content/fr'

		[languages.fr.params]
			contentTypeName = "posts"
			menuMore = "Plus"
			writtenBy = "Écrit par"
			readMore = "Lire la suite"
			readOtherPosts = "Lire d'autres postes"
			newerPosts = "Postes plus récents"
			olderPosts = "Postes plus anciens"
			minuteReadingTime = "temps de lecture"

		[languages.fr.params.logo]
			logoText = "home"
			logoHomeLink = "/"

		[languages.fr.menu]
			[[languages.fr.menu.main]]
				identifier = "about"
				weight = 1
				name = "A propos de moi"
				url = "/a-propos"

			[[languages.fr.menu.main]]
				identifier = "blog"
				weight = 2
				name = "Blog"
				url = "/blog"

			[[languages.fr.menu.main]]
				identifier = "recipes"
				weight = 4
				name = "Recettes"
				url = "/recettes"

			[[languages.fr.menu.main]]
				identifier = "contact"
				weight = 5
				name = "Me contacter"
				url = "/contact"


	[languages.en]
    	languageName = 'English'
		weight = 2
		contentDir = 'content/en'

		[languages.en.params]
			contentTypeName = "posts"
			menuMore = "Show more"
			writtenBy = "Written by"
			readMore = "Read more"
			readOtherPosts = "Read other posts"
			newerPosts = "Newer posts"
			olderPosts = "Older posts"
			minuteReadingTime = "min read"

		[languages.en.params.logo]
			logoText = "home"
			logoHomeLink = "/en"

		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "about"
				weight = 1
				name = "About me"
				url = "/en/about"

			[[languages.en.menu.main]]
				identifier = "blog"
				weight = 2
				name = "Blog"
				url = "/en/blog"

			[[languages.en.menu.main]]
				identifier = "recipes"
				weight = 4
				name = "Recipes"
				url = "/en/recipes"

			[[languages.en.menu.main]]
				identifier = "contact"
				weight = 5
				name = "Contact me"
				url = "/en/contact"
